# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vol2_bravo_development

test:
  <<: *default
  database: vol2_bravo_test

production:
  <<: *default
  database: vol2_bravo_production
  username: vol2_bravo
  password: <%= ENV['VOL2-BRAVO_DATABASE_PASSWORD'] %>
