# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vol2-bravo_development

test:
  <<: *default
  database: vol2-bravo_test

production:
  <<: *default
  database: vol2-bravo_production
  username: vol2-bravo
  password: <%= ENV['VOL2-BRAVO_DATABASE_PASSWORD'] %>
